### PR TITLE
Bernard Bussy wants to come as well please

### PR DESCRIPTION
**Pull request by BRBussy**
I want to come as well.

### CODE REVIEW

**Review by mgm1313 — APPROVED** [review]
Pleasure to have you!

**Comment by BRBussy** [comment]
merge plz.

**Review by mgm1313 — CHANGES_REQUESTED** [review]
Can you make it a real hyperlink please, github treats this as an relative URL. Thanks!

**Comment by BRBussy** [comment]
> Can you make it a real hyperlink please, github treats this as an relative URL. Thanks!

done :)

**Pull request merged**
